baseURL = "https://notesandshare.github.io/"
languageCode = "en-us"
title = "Notes and Share"
theme = "PaperMod"
relativeURLs = true
canonifyURLs = true
publishDir = "docs"

# Optional: enable syntax highlighting and summary
pagerSize = 10
summaryLength = 70

[params]
  author = "Your Name"
  description = "My technical blog built with Hugo and PaperMod"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  defaultTheme = "auto"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 3

[outputs]
  home = ["HTML", "RSS", "JSON"]


[security]
  [security.http]
    [security.http.headers]
      [security.http.headers.styleSrc]
        integrity = false  # disabled CSS SRI check